@extends('layouts.app')
@section('title', 'Products')
@section('page_title', 'Products')
@section('content')
<div class="d-flex justify-content-between mb-4"><p class="text-muted mb-0"><i class="fa-solid fa-boxes-stacked me-2"></i>SKU catalog, pricing, and stock levels.</p><a href="{{ route('products.create') }}" class="btn btn-primary rounded-pill"><i class="fa-solid fa-plus me-1"></i>Add Product</a></div>
<div class="card filter-card border-0 mb-4"><div class="card-body p-3"><form method="GET" class="row g-2"><div class="col-md-4"><input name="search" class="form-control" placeholder="Search SKU or name" value="{{ request('search') }}"></div><div class="col-md-3"><select name="category_id" class="form-select form-select-compact"><option value="">All Categories</option>@foreach($categories as $cat)<option value="{{ $cat->id }}" @selected(request('category_id')==$cat->id)>{{ $cat->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="status" class="form-select form-select-compact"><option value="">All Status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-dark w-100">Filter</button><a href="{{ route('products.index',['low_stock'=>1]) }}" class="btn btn-outline-danger w-100">Low Stock</a></div></form></div></div>
<div class="card card-table border-0"><div class="table-responsive"><table class="table mb-0"><thead class="table-light"><tr><th style="width:56px;"></th><th>SKU</th><th>Name</th><th>Category</th><th>Stock</th><th>Cost</th><th>Price</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($products as $product)
<tr>
<td>@if($product->image_path)<img src="{{ media_url($product->image_path) }}" alt="{{ $product->name }}" style="width:40px;height:40px;object-fit:cover;border-radius:6px;">@else<span class="text-muted"><i class="fa-regular fa-image"></i></span>@endif</td>
<td>{{ $product->sku }}</td><td><a href="{{ route('products.show',$product) }}" class="fw-bold text-decoration-none">{{ $product->name }}</a>@if($product->isLowStock()) <span class="badge bg-danger-subtle text-danger">Low</span>@endif</td><td>{{ $product->category?->name ?? '-' }}</td><td>{{ $product->stock_qty }} {{ $product->unit }}</td><td>${{ number_format($product->cost_price,2) }}</td><td>${{ number_format($product->sale_price,2) }}</td>
<td class="text-end"><div class="table-actions"><a href="{{ route('products.show',$product) }}" class="btn btn-sm btn-outline-info" title="View"><i class="fa-solid fa-eye"></i></a><a href="{{ route('products.edit',$product) }}" class="btn btn-sm btn-outline-primary" title="Edit"><i class="fa-solid fa-pen"></i></a><button class="btn btn-sm btn-outline-danger" title="Delete" data-bs-toggle="modal" data-bs-target="#deleteModal" data-url="{{ route('products.destroy',$product) }}" data-name="{{ $product->name }}"><i class="fa-solid fa-trash"></i></button></div></td></tr>
@empty<tr><td colspan="8" class="text-center py-4 text-muted">No products found.</td></tr>@endforelse
</tbody></table></div>@include('components.table-pagination', ['paginator'=>$products, 'sorts'=>['created_at'=>'Created','name'=>'Name','sku'=>'SKU','stock_qty'=>'Stock','sale_price'=>'Price']])</div>
@endsection
